In [2]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
import seaborn as sns

In [3]:
client_test = pd.read_csv("data/client_test.csv")
invoice_test = pd.read_csv("data/invoice_test.csv")

In [4]:
print('counter_statue', invoice_test['counter_statue'].unique())
print('counter_type', invoice_test['counter_type'].unique())
print('tarif_type', invoice_test['tarif_type'].unique())
print('counter_code', invoice_test['counter_code'].unique())
print('reading_remarque', invoice_test['reading_remarque'].unique())
print('counter_coefficient', invoice_test['counter_coefficient'].unique())
print('months_number', invoice_test['months_number'].unique())

counter_statue [0 1 5 4 3 2]
counter_type ['ELEC' 'GAZ']
tarif_type [11 40 45 15 10 13 12 14  9 29 21  8 30 24 27 42]
counter_code [203 433 207   5 420  25 413 202 407  10 442 467 410 204 102 453 403 201
 565 532 210 600 214 101 450  40 506 483 305 310  65 325 317 307  16 222
 303 333 227]
reading_remarque [8 9 6 7]
counter_coefficient [ 1  2  0 21  4  3 10]
months_number [     8      4      2     12      6      1     10      3     16     20
     13      9     24     18      5     30     14      7     15     17
     28     11     32     36     40     22     26  84975     56     52
 211540 204304 362531 653216 221353 264560 418219 392841 371215 376986
 386117 398309 410486 425211 442116 433262 332143 471936 887827 882976
 873101 856944 845713 826319 433667 511842 563563 601025 235674 240029
 249437 258926 270572 284735 292735 300892 308774 323358 340773 350014
 866128 835815 815166 700819 671456 355389 612658 810650 801502 461519
 521918 530227 732355 721774 711577 691642 681681 501060 658692 227663
 774590 539326 634246 624054 592454 553440 643009 491854 581310 763966
 755900 482557 744396 277649 573985 317267     34     42     50     48
     68     21     46     25     38     64     47     60     44     37
  21479      0 112487 114924  96601 119712 101276 109282 106630     19
     74     31  83820  95037  93344  92001  90708  98084  96427  99817
  89131  85836  87413   2052    956  97761     80     23     62  21220
  27525  10286  11071  10627  26697  20773  22644   6838  27906  28256
  12340  24596  24270  22189  21705  27064  19695  23070   7597  23513
   8358   9457  24003  25179  18532   7216   7986   9882  20317  11483
  11905  12683  17570  15555   4213   4034   3514   3126  13203  18998
  19262   5201  13901  14990  14474  18048  17121  16619  15992   6098
   5670     49 683141 845807 828723 841197 854320 858208 865855 879970
 631905 625728 602283 325209 636704  44041 318935 116749 752940 774185
 799770 818801 311833 306283 300568 295836 290947 280500 747745 742579
 737929 732698 708740 276478 270117 265500 141939 244193 194813  88717
 286570 862462 404247 908029 916294 595234 587475 567250 563250 553002
 544829 526829 522162 469061 335338 464679 432766 426094 422094 418091
 413713 409522 397991 388603 900317 849983 330612 833524 342802 349904
 355139 358139 363808 368977 374679 814237 382011 665172 392900 460820
 495004 500208 512092 804360 165075 837157     29    234  43179  42455
  23857  24760  25425  26280  53699  58417   4737  99642  43701  46560
  13071   7593  11039  65836  95755  33129  40237  74439  71373  81419
  69610  86427  90526  93762  85055  16929  14226  23983  34587  43444
  66494  61173  57906  88360  85496  79952  98604   3204  73311  62602
  28392  37731  39595  54157  11723  14450  47409  32504   9179  90027
  20544  23827  26766  45443  35145  39182  42236  30371  11467  16031
   6198   2169  96746  91223  33508  49754  63535  65871  98346  26946
  11364  32834  49637  21974  19874     45  19009  23836 115544 170243
  25416  15790  30946 165579 241541 176882  28954 208974  12407 156822
 126377 174695 118361 109041  78651  47649  27498  27927 170913 172021
  26560 148930 202192  85048  52756  52843  75059  76303  51342  82650
  94557  96737 123919 210234 144792 211153 214960 129597 219985 216647
 139556 142392 136744  54307 222530 250341  64235 187127 103064 179842
  61963 105763 122674 227468 231043 248427 224201  56081 128342 247095
  58883 147369  99463 134104 146729  98472  49949  39251 204791  72529
 206577 182298 192657  35898  70481  42420  32739  45781     59     58
     72     54  36507  23369  51142  93927  36699  26699  61815  93078
 134036  84909  89907 110764  83300  74645 128696 131943  84232  49168
  67678  84075 100244  99450  83844 133836 125285 122440 119650 116036
 114834  50123  97655  69709  67307  66140  64423  55867  49835  50871
 117215 115782 108069 105372  98225 113194  26499  24840  98801  95617
  11112  10879  99253  24576  24467  11356  11615  11828  12348  10230
  18210  20385  22381  23987  24290  99073  10133  26449  25108     66
     67    137   8354 157614 155407 139518 174352 152316 151402 141415
 140002 169039 139142 179790 136203  71306  69167  66782 212811 212803
 179606 161095 153779 131259 212799 212775 196158 183563 181683  73403
 137803  75340  80735 134246 129202 117890 178579 108871 107757 107272
 106494 104001 101750  98432  94396  91088  86602  82778  77592 109822
 176676  34422 957255 957240 974274  49970 225704 578559 983164 348574
 214918 239703  54734 957181 955660 950424 287398   6812 584113 590740
  27189  35323 951522  70645  76956  44101 571653 611867 955417 619095
 955087 626404 961411 974195  27333 952918 956918 149389 990688 685482
 564444 676119 663801 657155 651901 644827 638884 631950 549232 461559
 428826 930143 954621 557267 419050 543591 535384 519625 598668 510550
 605001 679708 905681 894068 880682 850093 836860 816633 802827 779334
 763353 737668 714151 708048 703578 698665  62517 825889 746722 726474
 691093 669722 321492 270585 499014 171353 164182 158419 949972 144881
 139192 133358 125244 118036 110683 105803  98514  91904  81397  71173
  59251  39321  14756   5407 179328 186155 194206 200539 488247 472630
 448991 438969 395949 388840 380744 369167 337572 981777 328838 308673
 293772 278690 259999 251185 231721 220677 966971 208214 316481 949954
 948685     35   8744   8138   9774  13853   6770  28103   1269    849
  15083  23524  15498  22589  32621  32549  32185  28858  28332   6333
   8721  23020  30733  29777  29368  28090  26700   7559   7277   7024
  14173  14884  16381  17171  18378  19725  20920  27580  21716  22749
  23299  23702  23950  24459  24827  25080  25565   5577   2783  26320
  12726  32771  31715  33039  11518  13419   9999  12270  33011   8709
   8633   8389     27  20586  37082  13859  16995  77357  49779  34267
  39332  76470  84577  41139  32154  55715   6993   4107    566  71544
  66142  66135  63310  95099  58302  48456  39519  97637  97617   1888
  16812  16966  20218  22999  10560  59334  11789  45350  41319  31645
  29896  34304  23760  19815  15073  11806  51420  58868  64276  81155
  79207  85431  62349  91281  27649  24317  25037  18370   4734   5740
  19354  20095 487548 330338 545684 541979 537244 524509 516516 511674
 507087 502252 520460 302269 307578 324712 319842 316178 311306 484001
 492368 475506 466639 412360 497541 375149 367920 335014 384034 529432
 297269 340995 344661 350037 354556 533240 419314 422599 428605 359453
 441693 446381 452149 457262 461726 479681 415717 436359 362744 372301
 407573 379384 387669 393224 402323 397832  66450 105635  95839  53971
  85370  60276  74513  82521  77928  62279  62297  74108  66057  58682
  71685  71228  62098 574444 537942 531899 517214 498659 492622 491617
 476448 390854 475755 461477 455902 441918 434602 433496 481835 398328
 413841 455283 420575     41]

In [5]:
invoice_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1939730 entries, 0 to 1939729
Data columns (total 16 columns):
 #   Column                Dtype
---  ------                -----
 0   client_id             object
 1   invoice_date          object
 2   tarif_type            int64
 3   counter_number        int64
 4   counter_statue        int64
 5   counter_code          int64
 6   reading_remarque      int64
 7   counter_coefficient   int64
 8   consommation_level_1  int64
 9   consommation_level_2  int64
 10  consommation_level_3  int64
 11  consommation_level_4  int64
 12  old_index             int64
 13  new_index             int64
 14  months_number         int64
 15  counter_type          object
dtypes: int64(13), object(3)
memory usage: 236.8+ MB

In [6]:
client_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58069 entries, 0 to 58068
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   disrict        58069 non-null  int64
 1   client_id      58069 non-null  object
 2   client_catg    58069 non-null  int64
 3   region         58069 non-null  int64
 4   creation_date  58069 non-null  object
dtypes: int64(3), object(2)
memory usage: 2.2+ MB

In [7]:
invoice_test.head()

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,test_Client_0,2018-03-16,11,651208,0,203,8,1,755,0,0,0,19145,19900,8,ELEC
1,test_Client_0,2014-03-21,11,651208,0,203,8,1,1067,0,0,0,13725,14792,8,ELEC
2,test_Client_0,2014-07-17,11,651208,0,203,8,1,0,0,0,0,14792,14792,4,ELEC
3,test_Client_0,2015-07-13,11,651208,0,203,9,1,410,0,0,0,16122,16532,4,ELEC
4,test_Client_0,2016-07-19,11,651208,0,203,9,1,412,0,0,0,17471,17883,4,ELEC

In [8]:
invoice_test.query("months_number > 88")

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
48335,test_Client_11310,2003-07-01,11,99133408,1,506,6,1,5,49540,0,0,0,51948,84975,ELEC
55795,test_Client_11501,2013-03-05,45,5234763,0,40,6,1,3,9406,0,0,0,204304,211540,GAZ
55798,test_Client_11501,2013-02-04,45,5234763,0,40,6,1,3,9947,0,0,0,196652,204304,GAZ
55807,test_Client_11501,2015-06-01,45,5234763,0,40,9,1,3,9284,0,0,0,355389,362531,GAZ
55811,test_Client_11501,2017-02-08,45,5234763,0,40,9,1,3,13269,0,0,0,643009,653216,GAZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1777824,test_Client_5782,2010-04-01,40,3108730,0,10,9,1,3,7003,0,0,0,476448,481835,GAZ
1777825,test_Client_5782,2006-02-01,40,3108730,0,10,6,1,3,9716,0,0,0,390854,398328,GAZ
1777826,test_Client_5782,2006-05-05,40,3108730,0,10,9,1,3,20166,0,0,0,398328,413841,GAZ
1777827,test_Client_5782,2008-05-05,40,3108730,0,10,9,1,3,17374,0,0,0,441918,455283,GAZ
1777828,test_Client_5782,2007-02-01,40,3108730,0,10,6,1,3,8754,0,0,0,413841,420575,GAZ

# Data cleaning

In [ ]:
train = invoice_client_train.copy()
# counter_statue == 269375 -> can be droped, since there is just one observation and also the train_Client_53725 belong to only that observation 
train = train.query("counter_statue != 269375")
# counter_statue == 420 and reading_remarque == 5 and counter_code == 1 -> they are just one time in the same observation, so we can drop them as well
train = train.query("counter_statue != 420")
# replace string of int to int
train['counter_statue'] = train['counter_statue'].replace('0', 0)
train['counter_statue'] = train['counter_statue'].replace('1', 1)
train['counter_statue'] = train['counter_statue'].replace('4', 4)
train['counter_statue'] = train['counter_statue'].replace('5', 5)
# counter_statue == 769 and reading_remarque == 207 ???
train = train.query("counter_statue != 769")
# counter_statue == 618 and reading_remarque == 413 ???
train = train.query("counter_statue != 618")
# counter_statue == 46 and reading_remarque == 203 ???
train = train.query("counter_statue != 46")
#months_number > 88
train = train.query("months_number <= 88") # auch aus testdaten